default_config:
logger:
  default: error
  logs:
    custom_components.api-sensor: debug



api-sensor:
  username: my_username
  password: my_password
  sensor:
    - enabled: true
      name: My custom name